# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '' # was UA-112060364-2

# menu:
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Sample Posts',       url: 'sample-posts'}
#- {name: 'Documentation',      url: 'documentation'}
#- {name: 'About',              url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:   'https://www.linkedin.com/in/simonebadaruddin/'}
- {icon: 'github' , link:    'https://github.com/simonebadaruddin'}
- {icon: 'instagram', link:  'https://www.instagram.com/simonebadaruddin/'}
- {icon: 'envelope', link:   'mailto:simoneb@uoregon.edu'}
- {icon: 'codepen', link:    'https://codepen.io/simonebadaruddin'}
- {icon: 'deviantart', link: 'https://www.deviantart.com/simoneavalon'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share'

related_posts: 'Next...'

post_date_prefix: 'Written on'
